baseURL = "https://hajimetsuchiya.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
publishDir ="docs"
theme = "gohugo-theme-ananke"
[taxonomies]
tag = "tags"
